name: Build Flet APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Flet
        run: pip install -r requirements.txt

      - name: Build APK
        run: >
          flet build apk --yes
          --android-meta-data com.google.android.gms.ads.APPLICATION_ID="ca-app-pub-3940256099942544~3347511713"
        env:
          FLET_CLI_NO_RICH_OUTPUT: 1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/**/*.apk
